config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :rounds do
    member do
      get :add_holes
      get :add_hole_statistics
    end
  end
  resources :holes
  resources :hole_statistics
  resources :tee_boxes

  root 'landing#index'

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :course
  belongs_to :tee_box
  has_many :hole_statistics
  has_many :holes, through: :tee_box

  accepts_nested_attributes_for :course, :hole_statistics, :tee_box

  HOLES = 18

  def scorecard_metrics
    course_metrics + scoring_metrics
  end

  def course_metrics
    %w(yardage par handicap)
  end

  def scoring_metrics
    %w(score putts sand_shots
       penalties fir gir)
  end

  def statistics
    {
      length: length,
      par: par,
      score: score,
      "fir_%": fir_percentage,
      "gir_%": gir_percentage,
      "scrambling_%": scrambling_percentage,
      "sand_save_%": sand_save_percentage,
      putts: putts,
      eagles: eagles,
      birdies: birdies,
      pars: pars,
      bogies: bogies,
      "2_bogies_+": bogies_plus
    }
  end

  def length
    holes.sum(:yardage)
  end

  def par
    holes.sum(:par)
  end

  def putts
    hole_statistics.sum(:putts)
  end

  def eagles
    hole_statistics.select{|hole_stat| (hole_stat.hole.par - 2) == hole_stat.score }.size
  end

  def birdies
    hole_statistics.select{|hole_stat| (hole_stat.hole.par - 1) == hole_stat.score }.size
  end

  def pars
    hole_statistics.select{|hole_stat| hole_stat.hole.par == hole_stat.score }.size
  end

  def bogies
    hole_statistics.select{|hole_stat| (hole_stat.hole.par + 1) == hole_stat.score }.size
  end

  def bogies_plus
    hole_statistics.select{|hole_stat| (hole_stat.hole.par + 2) >= hole_stat.score }.size
  end

  def fir_percentage
    100 * fairways_hit.to_f / possible_fairways.to_f
  end

  def gir_percentage
    100 * greens_hit.to_f / 18.0
  end

  def scrambling_percentage
    greens_missed == 0 ? 0 : 100 * scrambled.to_f / greens_missed.to_f
  end

  def sand_save_percentage
    sand_shots == 0 ? 0 : 100 * sand_saves.to_f / sand_shots.to_f
  end

  private

  def fairways_hit
    hole_statistics.select{|hole_stat| hole_stat.fir && hole_stat.hole.par > 3}.size
  end

  def possible_fairways
    holes.select{|hole| hole.par > 3}.size
  end

  def greens_hit
    hole_statistics.select{|hole_stat| hole_stat.gir}.size
  end

  def greens_missed
    hole_statistics.select{|hole_stat| !hole_stat.gir}.size
  end

  def scrambled
    hole_statistics.select{|hole_stat| !hole_stat.gir && hole_stat.score <= hole_stat.hole.par}.size
  end

  def sand_shots
    hole_statistics.select{|hole_stat| hole_stat.sand_shots > 0}.size
  end

  def sand_saves
    hole_statistics.select{|hole_stat| hole_stat.sand_shots > 0 && hole_stat.score <= hole_stat.hole.par}.size
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def new
    @round = Round.new

    if new_round_params[:round][:course_id].present?
      @existing_courses = Course.all
      @course = Course.find new_round_params[:round][:course_id]
      @existing_tee_boxes = @course.tee_boxes
    else
      @course = Course.new
    end

    if new_round_params[:round][:tee_box_id].present?
      @tee_box = @course.tee_boxes.find(new_round_params[:round][:tee_box_id])
    else
      @tee_box = @course.tee_boxes.new
    end

    @round.course = @course
    @round.tee_box = @tee_box
  end

  def create
    @round = Round.create round_details_params
    @round.tee_box.course = @round.course
    @round.tee_box.save!
    redirect_to rounds_path
  end

  def edit
    @round = Round.find round_params
    @course = @round.course
    @tee_box = @round.tee_box
    @existing_courses = Course.all
  end

  def update
    round = Round.find round_holes_params[:id]
    round.attributes = round_holes_params[:round]
    round.save!

    redirect_to round_path(round)
  end

  def destroy
    round = Round.find round_params
    round.destroy
    redirect_to rounds_path
  end

  def index
    @rounds = Round.order(date_played: :desc)
    @existing_courses = Course.all
    @existing_tee_boxes = {}
    @existing_courses.each{|c| @existing_tee_boxes[c.id] = c.tee_boxes.select(:id, :name)}
  end

  def show
    @round = Round.find round_params
    @tee_box = @round.tee_box
  end

  def add_holes
    @round = Round.find round_params
    @tee_box = @round.tee_box
    unless @tee_box.holes.present?
      Round::HOLES.times do |position|
        @tee_box.holes.build(position: position + 1)
      end
    end
  end

  def add_hole_statistics
    @round = Round.find round_params
    @tee_box = @round.tee_box
    unless @round.hole_statistics.present?
      Round::HOLES.times do |position|
        @round.hole_statistics.build(position: position + 1)
      end
    end
    redirect_to action: "add_holes" unless @tee_box.holes.present?
  end

  private

  def round_params
    params.require(:id)
  end

  def round_details_params
    params.require(:round).permit(:date_played, :score, :course_id, :tee_box_id,
                                  course_attributes: [:city, :name, :state],
                                  tee_box_attributes: [:name, :rating, :slope])
  end

  def round_holes_params
    params.permit(:id, round: [:tee_box, :date_played, :score, :rating, :slope,
                               hole_statistics_attributes: [:id, :position, :score, :putts,
                                                            :fir, :gir, :sand_shots,
                                                            :hole_id, :penalties]])
  end

  def new_round_params
    params.permit(round: [:course_id, :tee_box_id])
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  def course_display(round)
    course = round.course

    content_tag :div do
      content_tag(:div, course.name) +
        content_tag(:div, course.location)
    end
  end
end

app/views/rounds/_form.html.haml
=form_for round do |f|
  .row
    -if @existing_courses.present? || @course.persisted?
      .col.s6
        .row
          .col.s12
            %p Existing Course:

        .row
          .col.s12
            =f.hidden_field :course_id, value: @course.id
            =collection_select(:round, :course_id, @existing_courses, :id, :name, {prompt: "Select Existing Course..."}, {class: "browser-default", disabled: @course.persisted?})

    -else @course.new_record?
      .col.s6
        .row
          .col.s12
            %p New Course:

        =f.fields_for :course do |course_field|
          .row
            .input-field.col.s12
              =course_field.text_field :name
              =course_field.label :name

          .row
            .input-field.col.s6
              =course_field.text_field :city
              =course_field.label :city

            .input-field.col.s6
              =course_field.text_field :state
              =course_field.label :state

  .row
    =f.hidden_field :tee_box_id, value: @tee_box.id
    -if @tee_box.persisted?
      .col.s4
        %p="Tee Box: #{@tee_box.name}"
      .col.s4
        %p="Rating: #{@tee_box.rating}"
      .col.s4
        %p="Slope: #{@tee_box.slope}"

    -else
      =f.fields_for :tee_box do |tee_box_fields|
        .input-field.col.s3
          =tee_box_fields.text_field :name, required: true
          =tee_box_fields.label :name, "Tee Box", class:"#{round.tee_box.name.nil? ? '' : 'active'}"

        .input-field.col.s3
          =tee_box_fields.number_field :rating, min: 67, max: 77, step: 0.1, required: true
          =tee_box_fields.label :rating, "Course Rating", class:"#{round.tee_box.rating.nil? ? '' : 'active'}"

        .input-field.col.s3
          =tee_box_fields.number_field :slope, min: 55, max: 155, step: 1, required: true
          =tee_box_fields.label :slope, "Course Slope", class:"#{round.tee_box.slope.nil? ? '' : 'active'}"

  .row
    .input-field.col.s3
      =f.number_field :score, min: 50, max: 150, step: 1, required: true
      =f.label :score, "Score", class:"#{round.score.nil? ? '' : 'active'}"

  .row
    .col.s3
      =f.label :date_played
      =f.date_field :date_played, class: "datepicker", required: true

  .row
    .col.s12
      =submit_tag "Save Round", class: 'btn'
      =link_to "Cancel", :back

app/views/rounds/_round.html.haml
%tr
  -Course.statistics.each do |stat|
    %td
      -if TeeBox.statistics.include? stat
        %span=round.tee_box.send(stat)
      -else
        %span=round.send(stat)
  %td
    %span=round.course.name
  %td
    %span=round.course.location
  %td
    =link_to "Edit Round", edit_round_path(round)
    -if round.tee_box.holes.present?
      %span=" | "
      -if round.hole_statistics.present?
        -link_label = "Edit Hole Stats"
      -else
        -link_label = "Add Hole Stats To Scorecard"
      =link_to link_label, add_hole_statistics_round_path(round)

    -else
      %span=" | "
      =link_to "Add Holes To Tee Box", add_holes_round_path(round)

    %span=" | "
    =link_to "Delete", round, method: :delete, data:{confirm: "Are you sure?"}

app/views/rounds/_round_header.html.haml
%thead
  %tr
    -Course.statistics.each do |stat|
      %th
        -if stat == 'name'
          %span Tee Box
        -else
          %span=stat.humanize.titleize
    %th
      %span Course
    %th
      %span Location
    %th
      %span Actions

app/views/rounds/add_hole_statistics.html.haml
.container
  .row
    .col.s12
      %h3=@round.course.name
      %span="Date Played: #{@round.date_played}"

  =form_for @round do |f|
    .row
      .col.s12
        %table.highlight
          =f.fields_for :hole_statistics do |hole_statistics_field|
            -hole_stat = hole_statistics_field.object
            -hole = @tee_box.holes.find_by(position: hole_stat.position)
            =hole_statistics_field.hidden_field :hole_id, value: hole.id
            %tr
              %td
                %span=hole.position
              -@round.scoring_metrics.each do |metric|
                %td
                  -if %w(fir gir).include? metric
                    =hole_statistics_field.check_box metric.to_sym, {}, "true", "false"
                    =hole_statistics_field.label metric.to_sym, metric.upcase, class:"#{hole_stat.send(metric).nil? ? '' : 'active'}"
                  -else
                    .input-field
                      =hole_statistics_field.number_field metric.to_sym
                      =hole_statistics_field.label metric.to_sym, class:"#{hole_stat.send(metric).nil? ? '' : 'active'}"

    .row
      .col.s12
        =submit_tag "Save Hole Stats", class: 'btn'
        =link_to "Cancel", :back

app/views/rounds/add_holes.html.haml
.container
  .row
    .col.s12
      %h3=@round.course.name
      %span="Date Played: #{@round.date_played}"

  =form_for @tee_box do |f|
    .row
      .col.s12
        %table.highlight
          =f.fields_for :holes do |holes_field|
            -hole = holes_field.object
            %tr
              %td
                %span=hole.position
                =holes_field.hidden_field :position, value: hole.position
              -@tee_box.hole_metrics.each do |metric|
                %td
                  .input-field
                    =holes_field.number_field metric.to_sym
                    =holes_field.label metric.to_sym, class:"#{hole.send(metric).nil? ? '' : 'active'}"
    .row
      .col.s12
        =submit_tag "Save Holes", class: 'btn'

app/views/rounds/create.html.haml
%h1 Rounds#create
%p Find me in app/views/rounds/create.html.haml

app/views/rounds/edit.html.haml
.container
  .row
    .col.s12
      %h4 Edit Round At #{@course.name} From #{@round.date_played}

  =render partial: 'form', object: @round, as: :round

app/views/rounds/index.html.haml
.container
  .row
    .col.s12
      %h3 All Rounds
  =form_tag new_round_path, method: :get do
    .row
      .col.s3
        =collection_select(:round, :course_id, @existing_courses, :id, :name, {prompt: "New Course"}, {class: "browser-default"})
      .col.s3
        %select.browser-default{name: 'round[tee_box_id]', data: {behavior: 'teeBoxSelect', values: @existing_tee_boxes.to_json, course_elm_id: 'round_course_id'}})
      .col.s4
        =submit_tag "Add Round", class: "btn"
  .row
    .col.s12
      %table.striped.centered
        =render 'round_header'
        %tbody
          =render @rounds

app/views/rounds/new.html.haml
.container
  .row
    .col.s12
      %h4 Add A Round

  =render partial: 'form', object: @round, as: :round

app/views/rounds/show.html.haml
.container
  .row
    .col.s12
      %h4 Round
  .row
    .col.s12
      %table.striped.centered
        =render 'round_header'
        %tbody
          =render @round
  .row
    .col.s12
      %h4 Scorecard
  .row
    .col.s12
      %table.striped.centered
        %thead
          %tr
            %th
              %span Hole
            -@round.scorecard_metrics.each do |metric|
              %th
                -if %w(fir gir).include? metric
                  %span=metric.humanize.upcase
                -else
                  %span=metric.humanize.titleize
        %tbody
          =render @round.hole_statistics

app/views/rounds/update.html.haml
%h1 Rounds#update
%p Find me in app/views/rounds/update.html.haml